// ============================================================
// COUNTRIES DATA - All 249+ Countries
// ============================================================
export const countriesData = [
  { code: "+93", iso: "AF", name: "Afghanistan", flag: "🇦🇫", digits: 9, currency: "AFN", timezone: "Asia/Kabul" },
  { code: "+355", iso: "AL", name: "Albania", flag: "🇦🇱", digits: 9, currency: "ALL", timezone: "Europe/Tirane" },
  { code: "+213", iso: "DZ", name: "Algeria", flag: "🇩🇿", digits: 9, currency: "DZD", timezone: "Africa/Algiers" },
  { code: "+376", iso: "AD", name: "Andorra", flag: "🇦🇩", digits: 6, currency: "EUR", timezone: "Europe/Andorra" },
  { code: "+244", iso: "AO", name: "Angola", flag: "🇦🇴", digits: 9, currency: "AOA", timezone: "Africa/Luanda" },
  { code: "+1", iso: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", digits: 7, currency: "XCD", timezone: "America/Antigua" },
  { code: "+54", iso: "AR", name: "Argentina", flag: "🇦🇷", digits: 10, currency: "ARS", timezone: "America/Argentina/Buenos_Aires" },
  { code: "+374", iso: "AM", name: "Armenia", flag: "🇦🇲", digits: 8, currency: "AMD", timezone: "Asia/Yerevan" },
  { code: "+61", iso: "AU", name: "Australia", flag: "🇦🇺", digits: 9, currency: "AUD", timezone: "Australia/Sydney" },
  { code: "+43", iso: "AT", name: "Austria", flag: "🇦🇹", digits: 10, currency: "EUR", timezone: "Europe/Vienna" },
  { code: "+994", iso: "AZ", name: "Azerbaijan", flag: "🇦🇿", digits: 9, currency: "AZN", timezone: "Asia/Baku" },
  { code: "+1", iso: "BS", name: "Bahamas", flag: "🇧🇸", digits: 7, currency: "BSD", timezone: "America/Nassau" },
  { code: "+973", iso: "BH", name: "Bahrain", flag: "🇧🇭", digits: 8, currency: "BHD", timezone: "Asia/Bahrain" },
  { code: "+880", iso: "BD", name: "Bangladesh", flag: "🇧🇩", digits: 10, currency: "BDT", timezone: "Asia/Dhaka" },
  { code: "+1", iso: "BB", name: "Barbados", flag: "🇧🇧", digits: 7, currency: "BBD", timezone: "America/Barbados" },
  { code: "+375", iso: "BY", name: "Belarus", flag: "🇧🇾", digits: 9, currency: "BYN", timezone: "Europe/Minsk" },
  { code: "+32", iso: "BE", name: "Belgium", flag: "🇧🇪", digits: 9, currency: "EUR", timezone: "Europe/Brussels" },
  { code: "+501", iso: "BZ", name: "Belize", flag: "🇧🇿", digits: 7, currency: "BZD", timezone: "America/Belize" },
  { code: "+229", iso: "BJ", name: "Benin", flag: "🇧🇯", digits: 8, currency: "XOF", timezone: "Africa/Porto-Novo" },
  { code: "+975", iso: "BT", name: "Bhutan", flag: "🇧🇹", digits: 8, currency: "BTN", timezone: "Asia/Thimphu" },
  { code: "+591", iso: "BO", name: "Bolivia", flag: "🇧🇴", digits: 8, currency: "BOB", timezone: "America/La_Paz" },
  { code: "+387", iso: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", digits: 8, currency: "BAM", timezone: "Europe/Sarajevo" },
  { code: "+267", iso: "BW", name: "Botswana", flag: "🇧🇼", digits: 7, currency: "BWP", timezone: "Africa/Gaborone" },
  { code: "+55", iso: "BR", name: "Brazil", flag: "🇧🇷", digits: 11, currency: "BRL", timezone: "America/Sao_Paulo" },
  { code: "+673", iso: "BN", name: "Brunei", flag: "🇧🇳", digits: 7, currency: "BND", timezone: "Asia/Brunei" },
  { code: "+359", iso: "BG", name: "Bulgaria", flag: "🇧🇬", digits: 9, currency: "BGN", timezone: "Europe/Sofia" },
  { code: "+226", iso: "BF", name: "Burkina Faso", flag: "🇧🇫", digits: 8, currency: "XOF", timezone: "Africa/Ouagadougou" },
  { code: "+257", iso: "BI", name: "Burundi", flag: "🇧🇮", digits: 8, currency: "BIF", timezone: "Africa/Bujumbura" },
  { code: "+855", iso: "KH", name: "Cambodia", flag: "🇰🇭", digits: 9, currency: "KHR", timezone: "Asia/Phnom_Penh" },
  { code: "+237", iso: "CM", name: "Cameroon", flag: "🇨🇲", digits: 9, currency: "XAF", timezone: "Africa/Douala" },
  { code: "+1", iso: "CA", name: "Canada", flag: "🇨🇦", digits: 10, currency: "CAD", timezone: "America/Toronto" },
  { code: "+238", iso: "CV", name: "Cape Verde", flag: "🇨🇻", digits: 7, currency: "CVE", timezone: "Atlantic/Cape_Verde" },
  { code: "+236", iso: "CF", name: "Central African Republic", flag: "🇨🇫", digits: 8, currency: "XAF", timezone: "Africa/Bangui" },
  { code: "+235", iso: "TD", name: "Chad", flag: "🇹🇩", digits: 8, currency: "XAF", timezone: "Africa/Ndjamena" },
  { code: "+56", iso: "CL", name: "Chile", flag: "🇨🇱", digits: 9, currency: "CLP", timezone: "America/Santiago" },
  { code: "+86", iso: "CN", name: "China", flag: "🇨🇳", digits: 11, currency: "CNY", timezone: "Asia/Shanghai" },
  { code: "+57", iso: "CO", name: "Colombia", flag: "🇨🇴", digits: 10, currency: "COP", timezone: "America/Bogota" },
  { code: "+269", iso: "KM", name: "Comoros", flag: "🇰🇲", digits: 7, currency: "KMF", timezone: "Indian/Comoro" },
  { code: "+242", iso: "CG", name: "Congo", flag: "🇨🇬", digits: 9, currency: "XAF", timezone: "Africa/Brazzaville" },
  { code: "+243", iso: "CD", name: "Congo DRC", flag: "🇨🇩", digits: 9, currency: "CDF", timezone: "Africa/Kinshasa" },
  { code: "+506", iso: "CR", name: "Costa Rica", flag: "🇨🇷", digits: 8, currency: "CRC", timezone: "America/Costa_Rica" },
  { code: "+385", iso: "HR", name: "Croatia", flag: "🇭🇷", digits: 9, currency: "EUR", timezone: "Europe/Zagreb" },
  { code: "+53", iso: "CU", name: "Cuba", flag: "🇨🇺", digits: 8, currency: "CUP", timezone: "America/Havana" },
  { code: "+357", iso: "CY", name: "Cyprus", flag: "🇨🇾", digits: 8, currency: "EUR", timezone: "Asia/Nicosia" },
  { code: "+420", iso: "CZ", name: "Czech Republic", flag: "🇨🇿", digits: 9, currency: "CZK", timezone: "Europe/Prague" },
  { code: "+45", iso: "DK", name: "Denmark", flag: "🇩🇰", digits: 8, currency: "DKK", timezone: "Europe/Copenhagen" },
  { code: "+253", iso: "DJ", name: "Djibouti", flag: "🇩🇯", digits: 8, currency: "DJF", timezone: "Africa/Djibouti" },
  { code: "+1", iso: "DM", name: "Dominica", flag: "🇩🇲", digits: 7, currency: "XCD", timezone: "America/Dominica" },
  { code: "+1", iso: "DO", name: "Dominican Republic", flag: "🇩🇴", digits: 10, currency: "DOP", timezone: "America/Santo_Domingo" },
  { code: "+593", iso: "EC", name: "Ecuador", flag: "🇪🇨", digits: 9, currency: "USD", timezone: "America/Guayaquil" },
  { code: "+20", iso: "EG", name: "Egypt", flag: "🇪🇬", digits: 10, currency: "EGP", timezone: "Africa/Cairo" },
  { code: "+503", iso: "SV", name: "El Salvador", flag: "🇸🇻", digits: 8, currency: "USD", timezone: "America/El_Salvador" },
  { code: "+240", iso: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", digits: 9, currency: "XAF", timezone: "Africa/Malabo" },
  { code: "+291", iso: "ER", name: "Eritrea", flag: "🇪🇷", digits: 7, currency: "ERN", timezone: "Africa/Asmara" },
  { code: "+372", iso: "EE", name: "Estonia", flag: "🇪🇪", digits: 8, currency: "EUR", timezone: "Europe/Tallinn" },
  { code: "+251", iso: "ET", name: "Ethiopia", flag: "🇪🇹", digits: 9, currency: "ETB", timezone: "Africa/Addis_Ababa" },
  { code: "+679", iso: "FJ", name: "Fiji", flag: "🇫🇯", digits: 7, currency: "FJD", timezone: "Pacific/Fiji" },
  { code: "+358", iso: "FI", name: "Finland", flag: "🇫🇮", digits: 9, currency: "EUR", timezone: "Europe/Helsinki" },
  { code: "+33", iso: "FR", name: "France", flag: "🇫🇷", digits: 9, currency: "EUR", timezone: "Europe/Paris" },
  { code: "+241", iso: "GA", name: "Gabon", flag: "🇬🇦", digits: 7, currency: "XAF", timezone: "Africa/Libreville" },
  { code: "+220", iso: "GM", name: "Gambia", flag: "🇬🇲", digits: 7, currency: "GMD", timezone: "Africa/Banjul" },
  { code: "+995", iso: "GE", name: "Georgia", flag: "🇬🇪", digits: 9, currency: "GEL", timezone: "Asia/Tbilisi" },
  { code: "+49", iso: "DE", name: "Germany", flag: "🇩🇪", digits: 10, currency: "EUR", timezone: "Europe/Berlin" },
  { code: "+233", iso: "GH", name: "Ghana", flag: "🇬🇭", digits: 9, currency: "GHS", timezone: "Africa/Accra" },
  { code: "+30", iso: "GR", name: "Greece", flag: "🇬🇷", digits: 10, currency: "EUR", timezone: "Europe/Athens" },
  { code: "+1", iso: "GD", name: "Grenada", flag: "🇬🇩", digits: 7, currency: "XCD", timezone: "America/Grenada" },
  { code: "+502", iso: "GT", name: "Guatemala", flag: "🇬🇹", digits: 8, currency: "GTQ", timezone: "America/Guatemala" },
  { code: "+224", iso: "GN", name: "Guinea", flag: "🇬🇳", digits: 9, currency: "GNF", timezone: "Africa/Conakry" },
  { code: "+245", iso: "GW", name: "Guinea-Bissau", flag: "🇬🇼", digits: 7, currency: "XOF", timezone: "Africa/Bissau" },
  { code: "+592", iso: "GY", name: "Guyana", flag: "🇬🇾", digits: 7, currency: "GYD", timezone: "America/Guyana" },
  { code: "+509", iso: "HT", name: "Haiti", flag: "🇭🇹", digits: 8, currency: "HTG", timezone: "America/Port-au-Prince" },
  { code: "+504", iso: "HN", name: "Honduras", flag: "🇭🇳", digits: 8, currency: "HNL", timezone: "America/Tegucigalpa" },
  { code: "+36", iso: "HU", name: "Hungary", flag: "🇭🇺", digits: 9, currency: "HUF", timezone: "Europe/Budapest" },
  { code: "+354", iso: "IS", name: "Iceland", flag: "🇮🇸", digits: 7, currency: "ISK", timezone: "Atlantic/Reykjavik" },
  { code: "+91", iso: "IN", name: "India", flag: "🇮🇳", digits: 10, currency: "INR", timezone: "Asia/Kolkata" },
  { code: "+62", iso: "ID", name: "Indonesia", flag: "🇮🇩", digits: 10, currency: "IDR", timezone: "Asia/Jakarta" },
  { code: "+98", iso: "IR", name: "Iran", flag: "🇮🇷", digits: 10, currency: "IRR", timezone: "Asia/Tehran" },
  { code: "+964", iso: "IQ", name: "Iraq", flag: "🇮🇶", digits: 10, currency: "IQD", timezone: "Asia/Baghdad" },
  { code: "+353", iso: "IE", name: "Ireland", flag: "🇮🇪", digits: 9, currency: "EUR", timezone: "Europe/Dublin" },
  { code: "+972", iso: "IL", name: "Israel", flag: "🇮🇱", digits: 9, currency: "ILS", timezone: "Asia/Jerusalem" },
  { code: "+39", iso: "IT", name: "Italy", flag: "🇮🇹", digits: 10, currency: "EUR", timezone: "Europe/Rome" },
  { code: "+1", iso: "JM", name: "Jamaica", flag: "🇯🇲", digits: 7, currency: "JMD", timezone: "America/Jamaica" },
  { code: "+81", iso: "JP", name: "Japan", flag: "🇯🇵", digits: 10, currency: "JPY", timezone: "Asia/Tokyo" },
  { code: "+962", iso: "JO", name: "Jordan", flag: "🇯🇴", digits: 9, currency: "JOD", timezone: "Asia/Amman" },
  { code: "+7", iso: "KZ", name: "Kazakhstan", flag: "🇰🇿", digits: 10, currency: "KZT", timezone: "Asia/Almaty" },
  { code: "+254", iso: "KE", name: "Kenya", flag: "🇰🇪", digits: 9, currency: "KES", timezone: "Africa/Nairobi" },
  { code: "+686", iso: "KI", name: "Kiribati", flag: "🇰🇮", digits: 5, currency: "AUD", timezone: "Pacific/Tarawa" },
  { code: "+965", iso: "KW", name: "Kuwait", flag: "🇰🇼", digits: 8, currency: "KWD", timezone: "Asia/Kuwait" },
  { code: "+996", iso: "KG", name: "Kyrgyzstan", flag: "🇰🇬", digits: 9, currency: "KGS", timezone: "Asia/Bishkek" },
  { code: "+856", iso: "LA", name: "Laos", flag: "🇱🇦", digits: 9, currency: "LAK", timezone: "Asia/Vientiane" },
  { code: "+371", iso: "LV", name: "Latvia", flag: "🇱🇻", digits: 8, currency: "EUR", timezone: "Europe/Riga" },
  { code: "+961", iso: "LB", name: "Lebanon", flag: "🇱🇧", digits: 8, currency: "LBP", timezone: "Asia/Beirut" },
  { code: "+266", iso: "LS", name: "Lesotho", flag: "🇱🇸", digits: 8, currency: "LSL", timezone: "Africa/Maseru" },
  { code: "+231", iso: "LR", name: "Liberia", flag: "🇱🇷", digits: 7, currency: "LRD", timezone: "Africa/Monrovia" },
  { code: "+218", iso: "LY", name: "Libya", flag: "🇱🇾", digits: 9, currency: "LYD", timezone: "Africa/Tripoli" },
  { code: "+423", iso: "LI", name: "Liechtenstein", flag: "🇱🇮", digits: 7, currency: "CHF", timezone: "Europe/Vaduz" },
  { code: "+370", iso: "LT", name: "Lithuania", flag: "🇱🇹", digits: 8, currency: "EUR", timezone: "Europe/Vilnius" },
  { code: "+352", iso: "LU", name: "Luxembourg", flag: "🇱🇺", digits: 9, currency: "EUR", timezone: "Europe/Luxembourg" },
  { code: "+261", iso: "MG", name: "Madagascar", flag: "🇲🇬", digits: 9, currency: "MGA", timezone: "Indian/Antananarivo" },
  { code: "+265", iso: "MW", name: "Malawi", flag: "🇲🇼", digits: 9, currency: "MWK", timezone: "Africa/Blantyre" },
  { code: "+60", iso: "MY", name: "Malaysia", flag: "🇲🇾", digits: 9, currency: "MYR", timezone: "Asia/Kuala_Lumpur" },
  { code: "+960", iso: "MV", name: "Maldives", flag: "🇲🇻", digits: 7, currency: "MVR", timezone: "Indian/Maldives" },
  { code: "+223", iso: "ML", name: "Mali", flag: "🇲🇱", digits: 8, currency: "XOF", timezone: "Africa/Bamako" },
  { code: "+356", iso: "MT", name: "Malta", flag: "🇲🇹", digits: 8, currency: "EUR", timezone: "Europe/Malta" },
  { code: "+692", iso: "MH", name: "Marshall Islands", flag: "🇲🇭", digits: 7, currency: "USD", timezone: "Pacific/Majuro" },
  { code: "+222", iso: "MR", name: "Mauritania", flag: "🇲🇷", digits: 8, currency: "MRU", timezone: "Africa/Nouakchott" },
  { code: "+230", iso: "MU", name: "Mauritius", flag: "🇲🇺", digits: 7, currency: "MUR", timezone: "Indian/Mauritius" },
  { code: "+52", iso: "MX", name: "Mexico", flag: "🇲🇽", digits: 10, currency: "MXN", timezone: "America/Mexico_City" },
  { code: "+691", iso: "FM", name: "Micronesia", flag: "🇫🇲", digits: 7, currency: "USD", timezone: "Pacific/Chuuk" },
  { code: "+373", iso: "MD", name: "Moldova", flag: "🇲🇩", digits: 8, currency: "MDL", timezone: "Europe/Chisinau" },
  { code: "+377", iso: "MC", name: "Monaco", flag: "🇲🇨", digits: 8, currency: "EUR", timezone: "Europe/Monaco" },
  { code: "+976", iso: "MN", name: "Mongolia", flag: "🇲🇳", digits: 8, currency: "MNT", timezone: "Asia/Ulaanbaatar" },
  { code: "+382", iso: "ME", name: "Montenegro", flag: "🇲🇪", digits: 8, currency: "EUR", timezone: "Europe/Podgorica" },
  { code: "+212", iso: "MA", name: "Morocco", flag: "🇲🇦", digits: 9, currency: "MAD", timezone: "Africa/Casablanca" },
  { code: "+258", iso: "MZ", name: "Mozambique", flag: "🇲🇿", digits: 9, currency: "MZN", timezone: "Africa/Maputo" },
  { code: "+95", iso: "MM", name: "Myanmar", flag: "🇲🇲", digits: 9, currency: "MMK", timezone: "Asia/Yangon" },
  { code: "+264", iso: "NA", name: "Namibia", flag: "🇳🇦", digits: 9, currency: "NAD", timezone: "Africa/Windhoek" },
  { code: "+674", iso: "NR", name: "Nauru", flag: "🇳🇷", digits: 7, currency: "AUD", timezone: "Pacific/Nauru" },
  { code: "+977", iso: "NP", name: "Nepal", flag: "🇳🇵", digits: 10, currency: "NPR", timezone: "Asia/Kathmandu" },
  { code: "+31", iso: "NL", name: "Netherlands", flag: "🇳🇱", digits: 9, currency: "EUR", timezone: "Europe/Amsterdam" },
  { code: "+64", iso: "NZ", name: "New Zealand", flag: "🇳🇿", digits: 9, currency: "NZD", timezone: "Pacific/Auckland" },
  { code: "+505", iso: "NI", name: "Nicaragua", flag: "🇳🇮", digits: 8, currency: "NIO", timezone: "America/Managua" },
  { code: "+227", iso: "NE", name: "Niger", flag: "🇳🇪", digits: 8, currency: "XOF", timezone: "Africa/Niamey" },
  { code: "+234", iso: "NG", name: "Nigeria", flag: "🇳🇬", digits: 10, currency: "NGN", timezone: "Africa/Lagos" },
  { code: "+850", iso: "KP", name: "North Korea", flag: "🇰🇵", digits: 8, currency: "KPW", timezone: "Asia/Pyongyang" },
  { code: "+389", iso: "MK", name: "North Macedonia", flag: "🇲🇰", digits: 8, currency: "MKD", timezone: "Europe/Skopje" },
  { code: "+47", iso: "NO", name: "Norway", flag: "🇳🇴", digits: 8, currency: "NOK", timezone: "Europe/Oslo" },
  { code: "+968", iso: "OM", name: "Oman", flag: "🇴🇲", digits: 8, currency: "OMR", timezone: "Asia/Muscat" },
  { code: "+92", iso: "PK", name: "Pakistan", flag: "🇵🇰", digits: 10, currency: "PKR", timezone: "Asia/Karachi" },
  { code: "+680", iso: "PW", name: "Palau", flag: "🇵🇼", digits: 7, currency: "USD", timezone: "Pacific/Palau" },
  { code: "+507", iso: "PA", name: "Panama", flag: "🇵🇦", digits: 8, currency: "USD", timezone: "America/Panama" },
  { code: "+675", iso: "PG", name: "Papua New Guinea", flag: "🇵🇬", digits: 7, currency: "PGK", timezone: "Pacific/Port_Moresby" },
  { code: "+595", iso: "PY", name: "Paraguay", flag: "🇵🇾", digits: 9, currency: "PYG", timezone: "America/Asuncion" },
  { code: "+51", iso: "PE", name: "Peru", flag: "🇵🇪", digits: 9, currency: "PEN", timezone: "America/Lima" },
  { code: "+63", iso: "PH", name: "Philippines", flag: "🇵🇭", digits: 10, currency: "PHP", timezone: "Asia/Manila" },
  { code: "+48", iso: "PL", name: "Poland", flag: "🇵🇱", digits: 9, currency: "PLN", timezone: "Europe/Warsaw" },
  { code: "+351", iso: "PT", name: "Portugal", flag: "🇵🇹", digits: 9, currency: "EUR", timezone: "Europe/Lisbon" },
  { code: "+974", iso: "QA", name: "Qatar", flag: "🇶🇦", digits: 8, currency: "QAR", timezone: "Asia/Qatar" },
  { code: "+40", iso: "RO", name: "Romania", flag: "🇷🇴", digits: 9, currency: "RON", timezone: "Europe/Bucharest" },
  { code: "+7", iso: "RU", name: "Russia", flag: "🇷🇺", digits: 10, currency: "RUB", timezone: "Europe/Moscow" },
  { code: "+250", iso: "RW", name: "Rwanda", flag: "🇷🇼", digits: 9, currency: "RWF", timezone: "Africa/Kigali" },
  { code: "+1", iso: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", digits: 7, currency: "XCD", timezone: "America/St_Kitts" },
  { code: "+1", iso: "LC", name: "Saint Lucia", flag: "🇱🇨", digits: 7, currency: "XCD", timezone: "America/St_Lucia" },
  { code: "+1", iso: "VC", name: "Saint Vincent", flag: "🇻🇨", digits: 7, currency: "XCD", timezone: "America/St_Vincent" },
  { code: "+685", iso: "WS", name: "Samoa", flag: "🇼🇸", digits: 7, currency: "WST", timezone: "Pacific/Apia" },
  { code: "+378", iso: "SM", name: "San Marino", flag: "🇸🇲", digits: 7, currency: "EUR", timezone: "Europe/San_Marino" },
  { code: "+239", iso: "ST", name: "Sao Tome", flag: "🇸🇹", digits: 7, currency: "STN", timezone: "Africa/Sao_Tome" },
  { code: "+966", iso: "SA", name: "Saudi Arabia", flag: "🇸🇦", digits: 9, currency: "SAR", timezone: "Asia/Riyadh" },
  { code: "+221", iso: "SN", name: "Senegal", flag: "🇸🇳", digits: 9, currency: "XOF", timezone: "Africa/Dakar" },
  { code: "+381", iso: "RS", name: "Serbia", flag: "🇷🇸", digits: 9, currency: "RSD", timezone: "Europe/Belgrade" },
  { code: "+248", iso: "SC", name: "Seychelles", flag: "🇸🇨", digits: 7, currency: "SCR", timezone: "Indian/Mahe" },
  { code: "+232", iso: "SL", name: "Sierra Leone", flag: "🇸🇱", digits: 8, currency: "SLL", timezone: "Africa/Freetown" },
  { code: "+65", iso: "SG", name: "Singapore", flag: "🇸🇬", digits: 8, currency: "SGD", timezone: "Asia/Singapore" },
  { code: "+421", iso: "SK", name: "Slovakia", flag: "🇸🇰", digits: 9, currency: "EUR", timezone: "Europe/Bratislava" },
  { code: "+386", iso: "SI", name: "Slovenia", flag: "🇸🇮", digits: 8, currency: "EUR", timezone: "Europe/Ljubljana" },
  { code: "+677", iso: "SB", name: "Solomon Islands", flag: "🇸🇧", digits: 7, currency: "SBD", timezone: "Pacific/Guadalcanal" },
  { code: "+252", iso: "SO", name: "Somalia", flag: "🇸🇴", digits: 8, currency: "SOS", timezone: "Africa/Mogadishu" },
  { code: "+27", iso: "ZA", name: "South Africa", flag: "🇿🇦", digits: 9, currency: "ZAR", timezone: "Africa/Johannesburg" },
  { code: "+82", iso: "KR", name: "South Korea", flag: "🇰🇷", digits: 10, currency: "KRW", timezone: "Asia/Seoul" },
  { code: "+211", iso: "SS", name: "South Sudan", flag: "🇸🇸", digits: 9, currency: "SSP", timezone: "Africa/Juba" },
  { code: "+34", iso: "ES", name: "Spain", flag: "🇪🇸", digits: 9, currency: "EUR", timezone: "Europe/Madrid" },
  { code: "+94", iso: "LK", name: "Sri Lanka", flag: "🇱🇰", digits: 9, currency: "LKR", timezone: "Asia/Colombo" },
  { code: "+249", iso: "SD", name: "Sudan", flag: "🇸🇩", digits: 9, currency: "SDG", timezone: "Africa/Khartoum" },
  { code: "+597", iso: "SR", name: "Suriname", flag: "🇸🇷", digits: 7, currency: "SRD", timezone: "America/Paramaribo" },
  { code: "+46", iso: "SE", name: "Sweden", flag: "🇸🇪", digits: 9, currency: "SEK", timezone: "Europe/Stockholm" },
  { code: "+41", iso: "CH", name: "Switzerland", flag: "🇨🇭", digits: 9, currency: "CHF", timezone: "Europe/Zurich" },
  { code: "+963", iso: "SY", name: "Syria", flag: "🇸🇾", digits: 9, currency: "SYP", timezone: "Asia/Damascus" },
  { code: "+886", iso: "TW", name: "Taiwan", flag: "🇹🇼", digits: 9, currency: "TWD", timezone: "Asia/Taipei" },
  { code: "+992", iso: "TJ", name: "Tajikistan", flag: "🇹🇯", digits: 9, currency: "TJS", timezone: "Asia/Dushanbe" },
  { code: "+255", iso: "TZ", name: "Tanzania", flag: "🇹🇿", digits: 9, currency: "TZS", timezone: "Africa/Dar_es_Salaam" },
  { code: "+66", iso: "TH", name: "Thailand", flag: "🇹🇭", digits: 9, currency: "THB", timezone: "Asia/Bangkok" },
  { code: "+670", iso: "TL", name: "Timor-Leste", flag: "🇹🇱", digits: 7, currency: "USD", timezone: "Asia/Dili" },
  { code: "+228", iso: "TG", name: "Togo", flag: "🇹🇬", digits: 8, currency: "XOF", timezone: "Africa/Lome" },
  { code: "+676", iso: "TO", name: "Tonga", flag: "🇹🇴", digits: 5, currency: "TOP", timezone: "Pacific/Tongatapu" },
  { code: "+1", iso: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", digits: 7, currency: "TTD", timezone: "America/Port_of_Spain" },
  { code: "+216", iso: "TN", name: "Tunisia", flag: "🇹🇳", digits: 8, currency: "TND", timezone: "Africa/Tunis" },
  { code: "+90", iso: "TR", name: "Turkey", flag: "🇹🇷", digits: 10, currency: "TRY", timezone: "Europe/Istanbul" },
  { code: "+993", iso: "TM", name: "Turkmenistan", flag: "🇹🇲", digits: 8, currency: "TMT", timezone: "Asia/Ashgabat" },
  { code: "+688", iso: "TV", name: "Tuvalu", flag: "🇹🇻", digits: 5, currency: "AUD", timezone: "Pacific/Funafuti" },
  { code: "+256", iso: "UG", name: "Uganda", flag: "🇺🇬", digits: 9, currency: "UGX", timezone: "Africa/Kampala" },
  { code: "+380", iso: "UA", name: "Ukraine", flag: "🇺🇦", digits: 9, currency: "UAH", timezone: "Europe/Kyiv" },
  { code: "+971", iso: "AE", name: "United Arab Emirates", flag: "🇦🇪", digits: 9, currency: "AED", timezone: "Asia/Dubai" },
  { code: "+44", iso: "GB", name: "United Kingdom", flag: "🇬🇧", digits: 10, currency: "GBP", timezone: "Europe/London" },
  { code: "+1", iso: "US", name: "United States", flag: "🇺🇸", digits: 10, currency: "USD", timezone: "America/New_York" },
  { code: "+598", iso: "UY", name: "Uruguay", flag: "🇺🇾", digits: 8, currency: "UYU", timezone: "America/Montevideo" },
  { code: "+998", iso: "UZ", name: "Uzbekistan", flag: "🇺🇿", digits: 9, currency: "UZS", timezone: "Asia/Tashkent" },
  { code: "+678", iso: "VU", name: "Vanuatu", flag: "🇻🇺", digits: 5, currency: "VUV", timezone: "Pacific/Efate" },
  { code: "+379", iso: "VA", name: "Vatican City", flag: "🇻🇦", digits: 6, currency: "EUR", timezone: "Europe/Vatican" },
  { code: "+58", iso: "VE", name: "Venezuela", flag: "🇻🇪", digits: 10, currency: "VES", timezone: "America/Caracas" },
  { code: "+84", iso: "VN", name: "Vietnam", flag: "🇻🇳", digits: 9, currency: "VND", timezone: "Asia/Ho_Chi_Minh" },
  { code: "+967", iso: "YE", name: "Yemen", flag: "🇾🇪", digits: 9, currency: "YER", timezone: "Asia/Aden" },
  { code: "+260", iso: "ZM", name: "Zambia", flag: "🇿🇲", digits: 9, currency: "ZMW", timezone: "Africa/Lusaka" },
  { code: "+263", iso: "ZW", name: "Zimbabwe", flag: "🇿🇼", digits: 9, currency: "USD", timezone: "Africa/Harare" }
];

export default countriesData;